services:
  _defaults:
    public: true

  # Logs
  scalexpert.handler.logs:
    class: ScalexpertPlugin\Handler\LogsHandler
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  scalexpert.handler.hash:
    class: ScalexpertPlugin\Handler\HashHandler

  # API client
  scalexpert.api.guzzle.client:
    class: GuzzleHttp\Client

  scalexpert.api.client:
    class: ScalexpertPlugin\Helper\API\Client
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@scalexpert.api.guzzle.client'
      - '@scalexpert.handler.logs'
      - '@doctrine.orm.default_entity_manager'
      - '@scalexpert.handler.hash'
      - '@scalexpert.conf.solution_formatter'

  # Helpers
  scalexpert.conf.solution_formatter:
    class: ScalexpertPlugin\Helper\SolutionFormatter

  # Services
  scalexpert.service.available_solutions:
    class: ScalexpertPlugin\Service\AvailableSolutionsService
    arguments:
      - '@scalexpert.api.client'
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.legacy.context'

  scalexpert.service.cart_insurance_products:
    class: ScalexpertPlugin\Service\CartInsuranceProductsService
    arguments:
      - '@scalexpert.api.client'
      - '@doctrine.orm.default_entity_manager'
      - '@scalexpert.service.available_solutions'
      - '@prestashop.adapter.legacy.configuration'

  scalexpert.service.insurances_subscriptions:
    class: ScalexpertPlugin\Service\InsurancesSubscriptionsService
    arguments:
      - '@scalexpert.api.client'
      - '@doctrine.orm.default_entity_manager'

  scalexpert.service.update_orders_states:
    class: ScalexpertPlugin\Service\UpdateOrdersStatesService
    arguments:
      - '@scalexpert.api.client'
      - '@scalexpert.service.order_updater'
      - '@prestashop.adapter.legacy.configuration'

  scalexpert.service.order_updater:
    class: ScalexpertPlugin\Service\OrderUpdaterService
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.legacy.context'

  scalexpert.service.insurance_configuration:
    class: ScalexpertPlugin\Form\Configuration\InsuranceConfigurationFormDataConfiguration
    arguments: [ '@prestashop.adapter.legacy.configuration' ]

  scalexpert.service.solution_sorter:
    class: ScalexpertPlugin\Service\SolutionSorterService

  # Handlers
  scalexpert.handler.solution_name:
    class: ScalexpertPlugin\Handler\SolutionNameHandler

  scalexpert.handler.insurance_name:
    class: ScalexpertPlugin\Handler\InsuranceNameHandler
